package odbc

// ODBC Handle types (opaque pointers)
type SQLHANDLE uintptr
type SQLHENV SQLHANDLE
type SQLHDBC SQLHANDLE
type SQLHSTMT SQLHANDLE
type SQLHDESC SQLHANDLE

// ODBC Integer types
type SQLSMALLINT int16
type SQLUSMALLINT uint16
type SQLINTEGER int32
type SQLUINTEGER uint32
type SQLLEN int64   // 64-bit for portability across platforms
type SQLULEN uint64 // 64-bit for portability across platforms
type SQLRETURN SQLSMALLINT

// ODBC Character types
type SQLCHAR byte
type SQLWCHAR uint16 // UTF-16 on Windows

// Handle type identifiers
const (
	SQL_HANDLE_ENV  SQLSMALLINT = 1
	SQL_HANDLE_DBC  SQLSMALLINT = 2
	SQL_HANDLE_STMT SQLSMALLINT = 3
	SQL_HANDLE_DESC SQLSMALLINT = 4
)

// Return codes
const (
	SQL_SUCCESS           SQLRETURN = 0
	SQL_SUCCESS_WITH_INFO SQLRETURN = 1
	SQL_ERROR             SQLRETURN = -1
	SQL_INVALID_HANDLE    SQLRETURN = -2
	SQL_NO_DATA           SQLRETURN = 100
	SQL_NEED_DATA         SQLRETURN = 99
	SQL_STILL_EXECUTING   SQLRETURN = 2
)

// Null handle constant
const SQL_NULL_HANDLE SQLHANDLE = 0

// ODBC version constants
const (
	SQL_OV_ODBC2 = 2
	SQL_OV_ODBC3 = 3
)

// Environment attributes
const (
	SQL_ATTR_ODBC_VERSION       SQLINTEGER = 200
	SQL_ATTR_CONNECTION_POOLING SQLINTEGER = 201
	SQL_ATTR_CP_MATCH           SQLINTEGER = 202
	SQL_ATTR_OUTPUT_NTS         SQLINTEGER = 10001
)

// Connection attributes
const (
	SQL_ATTR_AUTOCOMMIT      SQLINTEGER = 102
	SQL_ATTR_CONNECTION_DEAD SQLINTEGER = 1209
	SQL_ATTR_LOGIN_TIMEOUT   SQLINTEGER = 103
	SQL_ATTR_ACCESS_MODE     SQLINTEGER = 101
	SQL_ATTR_TXN_ISOLATION   SQLINTEGER = 108
)

// Autocommit values
const (
	SQL_AUTOCOMMIT_OFF = 0
	SQL_AUTOCOMMIT_ON  = 1
)

// Access mode values
const (
	SQL_MODE_READ_WRITE = 0
	SQL_MODE_READ_ONLY  = 1
)

// Transaction isolation levels
const (
	SQL_TXN_READ_UNCOMMITTED = 1
	SQL_TXN_READ_COMMITTED   = 2
	SQL_TXN_REPEATABLE_READ  = 4
	SQL_TXN_SERIALIZABLE     = 8
)

// Statement attributes
const (
	SQL_ATTR_CURSOR_TYPE        SQLINTEGER = 6
	SQL_ATTR_CONCURRENCY        SQLINTEGER = 7
	SQL_ATTR_ROW_ARRAY_SIZE     SQLINTEGER = 27
	SQL_ATTR_ROW_STATUS_PTR     SQLINTEGER = 25
	SQL_ATTR_ROWS_FETCHED       SQLINTEGER = 26
	SQL_ATTR_QUERY_TIMEOUT      SQLINTEGER = 0
	SQL_ATTR_MAX_ROWS           SQLINTEGER = 1
	SQL_ATTR_CURSOR_SCROLLABLE  SQLINTEGER = -1
	SQL_ATTR_CURSOR_SENSITIVITY SQLINTEGER = -2
)

// Cursor types
const (
	SQL_CURSOR_FORWARD_ONLY  = 0
	SQL_CURSOR_KEYSET_DRIVEN = 1
	SQL_CURSOR_DYNAMIC       = 2
	SQL_CURSOR_STATIC        = 3
)

// String terminator
const SQL_NTS SQLINTEGER = -3

// Null data indicators
const (
	SQL_NULL_DATA    SQLLEN = -1
	SQL_DATA_AT_EXEC SQLLEN = -2
)

// SQLDriverConnect options
const (
	SQL_DRIVER_NOPROMPT          SQLUSMALLINT = 0
	SQL_DRIVER_COMPLETE          SQLUSMALLINT = 1
	SQL_DRIVER_PROMPT            SQLUSMALLINT = 2
	SQL_DRIVER_COMPLETE_REQUIRED SQLUSMALLINT = 3
)

// SQL data types
const (
	SQL_UNKNOWN_TYPE   SQLSMALLINT = 0
	SQL_CHAR           SQLSMALLINT = 1
	SQL_NUMERIC        SQLSMALLINT = 2
	SQL_DECIMAL        SQLSMALLINT = 3
	SQL_INTEGER        SQLSMALLINT = 4
	SQL_SMALLINT       SQLSMALLINT = 5
	SQL_FLOAT          SQLSMALLINT = 6
	SQL_REAL           SQLSMALLINT = 7
	SQL_DOUBLE         SQLSMALLINT = 8
	SQL_DATETIME       SQLSMALLINT = 9
	SQL_VARCHAR        SQLSMALLINT = 12
	SQL_TYPE_DATE      SQLSMALLINT = 91
	SQL_TYPE_TIME      SQLSMALLINT = 92
	SQL_TYPE_TIMESTAMP SQLSMALLINT = 93
	SQL_LONGVARCHAR    SQLSMALLINT = -1
	SQL_BINARY         SQLSMALLINT = -2
	SQL_VARBINARY      SQLSMALLINT = -3
	SQL_LONGVARBINARY  SQLSMALLINT = -4
	SQL_BIGINT         SQLSMALLINT = -5
	SQL_TINYINT        SQLSMALLINT = -6
	SQL_BIT            SQLSMALLINT = -7
	SQL_WCHAR          SQLSMALLINT = -8
	SQL_WVARCHAR       SQLSMALLINT = -9
	SQL_WLONGVARCHAR   SQLSMALLINT = -10
	SQL_GUID           SQLSMALLINT = -11
)

// C data type identifiers for binding
const (
	SQL_SIGNED_OFFSET   SQLSMALLINT = -20
	SQL_UNSIGNED_OFFSET SQLSMALLINT = -22
)

const (
	SQL_C_CHAR      = SQL_CHAR
	SQL_C_LONG      = SQL_INTEGER
	SQL_C_SHORT     = SQL_SMALLINT
	SQL_C_FLOAT     = SQL_REAL
	SQL_C_DOUBLE    = SQL_DOUBLE
	SQL_C_NUMERIC   = SQL_NUMERIC
	SQL_C_DEFAULT   = 99
	SQL_C_DATE      = SQL_TYPE_DATE
	SQL_C_TIME      = SQL_TYPE_TIME
	SQL_C_TIMESTAMP = SQL_TYPE_TIMESTAMP
	SQL_C_BINARY    = SQL_BINARY
	SQL_C_BIT       = SQL_BIT
	SQL_C_WCHAR     = SQL_WCHAR
	SQL_C_SBIGINT   = SQL_BIGINT + SQL_SIGNED_OFFSET    // -25
	SQL_C_UBIGINT   = SQL_BIGINT + SQL_UNSIGNED_OFFSET  // -27
	SQL_C_SLONG     = SQL_C_LONG + SQL_SIGNED_OFFSET    // -16
	SQL_C_SSHORT    = SQL_C_SHORT + SQL_SIGNED_OFFSET   // -15
	SQL_C_STINYINT  = SQL_TINYINT + SQL_SIGNED_OFFSET   // -26
	SQL_C_ULONG     = SQL_C_LONG + SQL_UNSIGNED_OFFSET  // -18
	SQL_C_USHORT    = SQL_C_SHORT + SQL_UNSIGNED_OFFSET // -17
	SQL_C_UTINYINT  = SQL_TINYINT + SQL_UNSIGNED_OFFSET // -28
	SQL_C_GUID      = SQL_GUID
)

// Parameter input/output type
const (
	SQL_PARAM_INPUT        SQLSMALLINT = 1
	SQL_PARAM_INPUT_OUTPUT SQLSMALLINT = 2
	SQL_PARAM_OUTPUT       SQLSMALLINT = 4
)

// Fetch direction
const (
	SQL_FETCH_NEXT     SQLSMALLINT = 1
	SQL_FETCH_FIRST    SQLSMALLINT = 2
	SQL_FETCH_LAST     SQLSMALLINT = 3
	SQL_FETCH_PRIOR    SQLSMALLINT = 4
	SQL_FETCH_ABSOLUTE SQLSMALLINT = 5
	SQL_FETCH_RELATIVE SQLSMALLINT = 6
)

// Free statement options
const (
	SQL_CLOSE        SQLUSMALLINT = 0
	SQL_DROP         SQLUSMALLINT = 1
	SQL_UNBIND       SQLUSMALLINT = 2
	SQL_RESET_PARAMS SQLUSMALLINT = 3
)

// Transaction completion types
const (
	SQL_COMMIT   SQLSMALLINT = 0
	SQL_ROLLBACK SQLSMALLINT = 1
)

// Nullable field values
const (
	SQL_NO_NULLS         SQLSMALLINT = 0
	SQL_NULLABLE         SQLSMALLINT = 1
	SQL_NULLABLE_UNKNOWN SQLSMALLINT = 2
)

// Column attribute identifiers
const (
	SQL_DESC_COUNT                  SQLUSMALLINT = 1001
	SQL_DESC_TYPE                   SQLUSMALLINT = 1002
	SQL_DESC_LENGTH                 SQLUSMALLINT = 1003
	SQL_DESC_OCTET_LENGTH_PTR       SQLUSMALLINT = 1004
	SQL_DESC_PRECISION              SQLUSMALLINT = 1005
	SQL_DESC_SCALE                  SQLUSMALLINT = 1006
	SQL_DESC_DATETIME_INTERVAL_CODE SQLUSMALLINT = 1007
	SQL_DESC_NULLABLE               SQLUSMALLINT = 1008
	SQL_DESC_INDICATOR_PTR          SQLUSMALLINT = 1009
	SQL_DESC_DATA_PTR               SQLUSMALLINT = 1010
	SQL_DESC_NAME                   SQLUSMALLINT = 1011
	SQL_DESC_UNNAMED                SQLUSMALLINT = 1012
	SQL_DESC_OCTET_LENGTH           SQLUSMALLINT = 1013
	SQL_DESC_ALLOC_TYPE             SQLUSMALLINT = 1099
	SQL_DESC_CONCISE_TYPE           SQLUSMALLINT = SQL_DESC_TYPE
	SQL_DESC_DISPLAY_SIZE           SQLUSMALLINT = 6
	SQL_DESC_UNSIGNED               SQLUSMALLINT = 8
	SQL_DESC_UPDATABLE              SQLUSMALLINT = 10
	SQL_DESC_AUTO_UNIQUE_VALUE      SQLUSMALLINT = 11
	SQL_DESC_TYPE_NAME              SQLUSMALLINT = 14
	SQL_DESC_TABLE_NAME             SQLUSMALLINT = 15
	SQL_DESC_SCHEMA_NAME            SQLUSMALLINT = 16
	SQL_DESC_CATALOG_NAME           SQLUSMALLINT = 17
	SQL_DESC_BASE_COLUMN_NAME       SQLUSMALLINT = 22
	SQL_DESC_BASE_TABLE_NAME        SQLUSMALLINT = 23
	SQL_DESC_LABEL                  SQLUSMALLINT = 18
	SQL_COLUMN_LENGTH               SQLUSMALLINT = 3
	SQL_COLUMN_PRECISION            SQLUSMALLINT = 4
	SQL_COLUMN_SCALE                SQLUSMALLINT = 5
)

// SQLGetInfo information types
const (
	SQL_DRIVER_NAME           SQLUSMALLINT = 6
	SQL_DRIVER_VER            SQLUSMALLINT = 7
	SQL_DBMS_NAME             SQLUSMALLINT = 17
	SQL_DBMS_VER              SQLUSMALLINT = 18
	SQL_DATABASE_NAME         SQLUSMALLINT = 16
	SQL_SERVER_NAME           SQLUSMALLINT = 13
	SQL_USER_NAME             SQLUSMALLINT = 47
	SQL_IDENTIFIER_QUOTE_CHAR SQLUSMALLINT = 29
	SQL_MAX_IDENTIFIER_LEN    SQLUSMALLINT = 10005
)

// Timestamp struct for date/time binding
type SQL_TIMESTAMP_STRUCT struct {
	Year     SQLSMALLINT
	Month    SQLUSMALLINT
	Day      SQLUSMALLINT
	Hour     SQLUSMALLINT
	Minute   SQLUSMALLINT
	Second   SQLUSMALLINT
	Fraction SQLUINTEGER // billionths of a second
}

// Date struct
type SQL_DATE_STRUCT struct {
	Year  SQLSMALLINT
	Month SQLUSMALLINT
	Day   SQLUSMALLINT
}

// Time struct
type SQL_TIME_STRUCT struct {
	Hour   SQLUSMALLINT
	Minute SQLUSMALLINT
	Second SQLUSMALLINT
}

// Numeric struct for decimal/numeric types
type SQL_NUMERIC_STRUCT struct {
	Precision SQLCHAR
	Scale     SQLSCHAR
	Sign      SQLCHAR // 1 = positive, 0 = negative
	Val       [16]SQLCHAR
}

type SQLSCHAR int8

// IsSuccess checks if the return code indicates success
func IsSuccess(ret SQLRETURN) bool {
	return ret == SQL_SUCCESS || ret == SQL_SUCCESS_WITH_INFO
}
